<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.liam</groupId>
        <artifactId>huaxia</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>huaxia-common</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>huaxia-common-core</module>
        <module>huaxia-common-security</module>
        <module>huaxia-common-redis</module>
        <module>huaxia-common-rabbitmq</module>
        <module>huaxia-common-mybatis</module>
        <module>huaxia-common-elasticsearch</module>
        <module>huaxia-common-langchain4j</module>
        <module>huaxia-common-easyexcel</module>
        <module>huaxia-common-nlp</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>